-- mod-stellar-tarot — the boards, and the numbers around them.
--
-- axis 0 = a row, side 0 its left number and 1 its right one; axis 1 = a
-- column, side 0 its top number and 1 its bottom one. Every number may
-- differ from the one across.
--
-- GENERATED by the author's tooling. Regenerable.

DELETE FROM `mod_stellar_tarot_board_line`;
DELETE FROM `mod_stellar_tarot_board`;

INSERT INTO `mod_stellar_tarot_board` (`board_id`, `row_count`, `col_count`, `art`) VALUES
(1, 2, 2, ''),
(2, 3, 3, ''),
(3, 4, 2, '');

INSERT INTO `mod_stellar_tarot_board_line` (`board_id`, `axis`, `idx`, `side`, `number`) VALUES
(1, 0, 1, 0, 3),
(1, 0, 1, 1, 4),
(1, 0, 2, 0, 5),
(1, 0, 2, 1, 2),
(1, 1, 1, 0, 2),
(1, 1, 1, 1, 6),
(1, 1, 2, 0, 1),
(1, 1, 2, 1, 3),
(2, 0, 1, 0, 1),
(2, 0, 1, 1, 7),
(2, 0, 2, 0, 4),
(2, 0, 2, 1, 4),
(2, 0, 3, 0, 8),
(2, 0, 3, 1, 2),
(2, 1, 1, 0, 2),
(2, 1, 1, 1, 9),
(2, 1, 2, 0, 5),
(2, 1, 2, 1, 1),
(2, 1, 3, 0, 3),
(2, 1, 3, 1, 6),
(3, 0, 1, 0, 2),
(3, 0, 1, 1, 5),
(3, 0, 2, 0, 6),
(3, 0, 2, 1, 1),
(3, 0, 3, 0, 3),
(3, 0, 3, 1, 7),
(3, 0, 4, 0, 9),
(3, 0, 4, 1, 4),
(3, 1, 1, 0, 1),
(3, 1, 1, 1, 8),
(3, 1, 2, 0, 4),
(3, 1, 2, 1, 2);
