-- mod-stellar-tarot — the cards: edges, effects, tags.
--
-- One row per card: its four edges, its one tag, whether its levels stack (`cumulative`),
-- and per level a spell applied as an aura and/or a module script. THE
-- EFFECTS ARE PLACEHOLDERS: test auras of +1234 to one statistic per level
-- (the sentinel amount, until the powers are designed) and the module's two
-- example scripts.
--
-- GENERATED by the author's tooling. Regenerable.

DELETE FROM `mod_stellar_tarot_card_locale`;
DELETE FROM `mod_stellar_tarot_card`;
DELETE FROM `mod_stellar_tarot_tag_locale`;
DELETE FROM `mod_stellar_tarot_tag`;

INSERT INTO `mod_stellar_tarot_tag` (`tag_id`, `name`) VALUES
(1, 'Physical'),
(2, 'Magic'),
(3, 'Wealth'),
(4, 'Madness'),
(5, 'Misc.');

INSERT INTO `mod_stellar_tarot_tag_locale` (`tag_id`, `locale`, `name`) VALUES
(1, 'frFR', 'Physique'),
(2, 'frFR', 'Magie'),
(3, 'frFR', 'Richesse'),
(4, 'frFR', 'Folie'),
(5, 'frFR', 'Divers');

INSERT INTO `mod_stellar_tarot_card`
  (`card_id`, `name`, `edge_top`, `edge_right`, `edge_bottom`, `edge_left`, `tag_id`, `cumulative`,
   `card_spell_1`, `card_spell_2`, `card_spell_3`, `card_spell_4`,
   `card_script_1`, `card_script_2`, `card_script_3`, `card_script_4`, `hint`, `art`) VALUES
(1, 'The Star', 2, 5, 1, 1, 3, 1, 903004, 903005, 903006, 903007, '', '', '', '', 'Lorem ipsum', 'Interface\\mod-Tarot\\Cards\\the_star'),
(2, 'The Moon', 5, 3, 4, 5, 2, 1, 903008, 903009, 903010, 903011, '', '', '', '', 'Lorem ipsum', 'Interface\\mod-Tarot\\Cards\\the_moon'),
(3, 'The Sun', 3, 1, 2, 3, 1, 1, 903012, 903013, 903014, 903015, '', '', '', '', 'Lorem ipsum', 'Interface\\mod-Tarot\\Cards\\the_sun'),
(4, 'The Comet', 1, 4, 4, 2, 1, 1, 903016, 903017, 903018, 903019, '', '', '', 'gold_on_kill:1234', 'Lorem ipsum', 'Interface\\mod-Tarot\\Cards\\the_comet'),
(5, 'The Eclipse', 4, 2, 5, 4, 4, 1, 903020, 903021, 903022, 903023, '', '', '', '', 'Lorem ipsum', 'Interface\\mod-Tarot\\Cards\\the_eclipse'),
(6, 'The Nebula', 2, 1, 3, 2, 5, 1, 903024, 903025, 903026, 903027, '', '', '', '', 'Lorem ipsum', 'Interface\\mod-Tarot\\Cards\\the_nebula'),
(7, 'The Void', 5, 5, 1, 1, 4, 0, 903028, 903029, 903030, 903031, '', '', '', '', 'Lorem ipsum', 'Interface\\mod-Tarot\\Cards\\the_void'),
(8, 'The Wanderer', 4, 3, 2, 1, 5, 0, 903032, 0, 903034, 903035, '', 'heal_on_kill:12', '', '', 'Lorem ipsum', 'Interface\\mod-Tarot\\Cards\\the_wanderer'),
(9, 'The Twins', 3, 2, 3, 3, 1, 0, 903036, 903037, 903038, 903039, '', '', '', '', 'Lorem ipsum', 'Interface\\mod-Tarot\\Cards\\the_twins'),
(10, 'The Serpent', 2, 4, 8, 9, 5, 0, 903040, 903041, 903042, 903043, '', '', '', '', 'Lorem ipsum', 'Interface\\mod-Tarot\\Cards\\the_serpent'),
(11, 'The Lantern', 1, 1, 5, 4, 3, 0, 903044, 903045, 903046, 903047, '', '', '', '', 'Lorem ipsum', 'Interface\\mod-Tarot\\Cards\\the_lantern'),
(12, 'The Tide', 8, 2, 1, 5, 5, 0, 0, 0, 0, 903051, 'heal_on_kill:12', 'heal_on_kill:24', 'gold_on_kill:1234', 'gold_on_kill:1234', 'Lorem ipsum', 'Interface\\mod-Tarot\\Cards\\the_tide');

INSERT INTO `mod_stellar_tarot_card_locale` (`card_id`, `locale`, `hint`) VALUES
(1, 'frFR', 'Lorem ipsum'),
(2, 'frFR', 'Lorem ipsum'),
(3, 'frFR', 'Lorem ipsum'),
(4, 'frFR', 'Lorem ipsum'),
(5, 'frFR', 'Lorem ipsum'),
(6, 'frFR', 'Lorem ipsum'),
(7, 'frFR', 'Lorem ipsum'),
(8, 'frFR', 'Lorem ipsum'),
(9, 'frFR', 'Lorem ipsum'),
(10, 'frFR', 'Lorem ipsum'),
(11, 'frFR', 'Lorem ipsum'),
(12, 'frFR', 'Lorem ipsum');
