-- mod-stellar-tarot — the items: one per card, one per board.
--
-- Card N is item 902000 + N, board B is item 902500 + B. The names are the
-- names a player reads; the catalogue keeps the English one of reference.
--
-- The displays are the game's own (Darkmoon cards and decks): nothing to patch
-- in the client for the icons. Item.dbc is another matter -- the client needs
-- a row per item, and the installer merges data/dbc/stellartarot_Item.dbc
-- into its own file.
--
-- USE: every card carries spell 903000 and every board spell 903001, cast on
-- use (trigger 0), no charge consumed by the cast (0): the module intercepts
-- the use server side, studies the item into the account's binder and destroys
-- it itself. See stellar_tarot_07_spells.sql.
--
-- GENERATED by the author's tooling. Regenerable: every block deletes its own
-- range before writing it again.

DELETE FROM `item_template` WHERE `entry` BETWEEN 902001 AND 902599;
DELETE FROM `item_template_locale` WHERE `ID` BETWEEN 902001 AND 902599;
DELETE FROM `item_dbc` WHERE `ID` BETWEEN 902001 AND 902599;

INSERT INTO `item_template`
  (`entry`, `class`, `subclass`, `name`, `displayid`, `Quality`, `Flags`, `BuyCount`,
   `BuyPrice`, `SellPrice`, `InventoryType`, `ItemLevel`, `RequiredLevel`, `bonding`,
   `stackable`, `MaxDurability`, `description`, `ScriptName`,
   `spellid_1`, `spelltrigger_1`, `spellcharges_1`) VALUES
(902001, 15, 4, 'The Star', 31756, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 'A card of the stellar tarot.', '', 903000, 0, 0),
(902002, 15, 4, 'The Moon', 31760, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 'A card of the stellar tarot.', '', 903000, 0, 0),
(902003, 15, 4, 'The Sun', 31762, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 'A card of the stellar tarot.', '', 903000, 0, 0),
(902004, 15, 4, 'The Comet', 31767, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 'A card of the stellar tarot.', '', 903000, 0, 0),
(902005, 15, 4, 'The Eclipse', 31756, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 'A card of the stellar tarot.', '', 903000, 0, 0),
(902006, 15, 4, 'The Nebula', 31760, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 'A card of the stellar tarot.', '', 903000, 0, 0),
(902007, 15, 4, 'The Void', 31762, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 'A card of the stellar tarot.', '', 903000, 0, 0),
(902008, 15, 4, 'The Wanderer', 31767, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 'A card of the stellar tarot.', '', 903000, 0, 0),
(902009, 15, 4, 'The Twins', 31756, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 'A card of the stellar tarot.', '', 903000, 0, 0),
(902010, 15, 4, 'The Serpent', 31760, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 'A card of the stellar tarot.', '', 903000, 0, 0),
(902011, 15, 4, 'The Lantern', 31762, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 'A card of the stellar tarot.', '', 903000, 0, 0),
(902012, 15, 4, 'The Tide', 31767, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 'A card of the stellar tarot.', '', 903000, 0, 0),
(902501, 15, 4, 'Novice''s Board', 31755, 3, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 'A board of the stellar tarot.', '', 903001, 0, 0),
(902502, 15, 4, 'Wanderer''s Board', 31755, 3, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 'A board of the stellar tarot.', '', 903001, 0, 0),
(902503, 15, 4, 'Astral Board', 31755, 3, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 'A board of the stellar tarot.', '', 903001, 0, 0);

INSERT INTO `item_template_locale` (`ID`, `locale`, `Name`, `Description`) VALUES
(902001, 'frFR', 'L''Étoile', 'Une carte du tarot stellaire.'),
(902002, 'frFR', 'La Lune', 'Une carte du tarot stellaire.'),
(902003, 'frFR', 'Le Soleil', 'Une carte du tarot stellaire.'),
(902004, 'frFR', 'La Comète', 'Une carte du tarot stellaire.'),
(902005, 'frFR', 'L''Éclipse', 'Une carte du tarot stellaire.'),
(902006, 'frFR', 'La Nébuleuse', 'Une carte du tarot stellaire.'),
(902007, 'frFR', 'Le Vide', 'Une carte du tarot stellaire.'),
(902008, 'frFR', 'Le Vagabond', 'Une carte du tarot stellaire.'),
(902009, 'frFR', 'Les Jumeaux', 'Une carte du tarot stellaire.'),
(902010, 'frFR', 'Le Serpent', 'Une carte du tarot stellaire.'),
(902011, 'frFR', 'La Lanterne', 'Une carte du tarot stellaire.'),
(902012, 'frFR', 'La Marée', 'Une carte du tarot stellaire.'),
(902501, 'frFR', 'Plateau du novice', 'Un plateau du tarot stellaire.'),
(902502, 'frFR', 'Plateau du vagabond', 'Un plateau du tarot stellaire.'),
(902503, 'frFR', 'Plateau astral', 'Un plateau du tarot stellaire.');

INSERT INTO `item_dbc`
  (`ID`, `ClassID`, `SubclassID`, `Sound_Override_Subclassid`, `Material`,
   `DisplayInfoID`, `InventoryType`, `SheatheType`) VALUES
(902001, 15, 4, -1, 0, 31756, 0, 0),
(902002, 15, 4, -1, 0, 31760, 0, 0),
(902003, 15, 4, -1, 0, 31762, 0, 0),
(902004, 15, 4, -1, 0, 31767, 0, 0),
(902005, 15, 4, -1, 0, 31756, 0, 0),
(902006, 15, 4, -1, 0, 31760, 0, 0),
(902007, 15, 4, -1, 0, 31762, 0, 0),
(902008, 15, 4, -1, 0, 31767, 0, 0),
(902009, 15, 4, -1, 0, 31756, 0, 0),
(902010, 15, 4, -1, 0, 31760, 0, 0),
(902011, 15, 4, -1, 0, 31762, 0, 0),
(902012, 15, 4, -1, 0, 31767, 0, 0),
(902501, 15, 4, -1, 0, 31755, 0, 0),
(902502, 15, 4, -1, 0, 31755, 0, 0),
(902503, 15, 4, -1, 0, 31755, 0, 0);
