-- mod-stellar-tarot — the spells the client must know.
--
-- Two spells do nothing: 903000 sits on every card and 903001 on every board,
-- so that the client lets the player USE the item -- a client sends nothing
-- for a spell it has no row for. The module intercepts the use server side
-- (ITEM_EVENT_ON_USE, in the Lua interface) and relays it to `.tarot study`,
-- which does the work; the cast never happens.
--
-- 903002 is the BANNER: the one aura the player sees while any effect is in
-- force; its text points at the window. The others are the TEST AURAS of the
-- cards: 903000 + 4 x card + (level - 1), one statistic each, +1234 --
-- placeholders until the powers are designed -- hidden from the aura bar
-- (AttributesEx 0x10000000, SPELL_ATTR1_NO_AURA_ICON) so that only the
-- banner shows. A card may name any spell instead, the game's own included.
--
-- The server reads these rows from `spell_dbc`; the client from
-- data/dbc/stellartarot_Spell.dbc, merged into its own file by the installer.
-- Both are written from the same source.
--
-- THE LANGUAGE COLUMN. A text block counts sixteen slots, and the client's
-- order is 0 enUS, 1 koKR, 2 frFR, 3 deDE... The columns of `spell_dbc` name
-- one more, `_Lang_enGB` at 1, and slide by one from there: the column holding
-- FRENCH is called `_Lang_koKR`, and the one called `_Lang_frFR` is German.
--
-- GENERATED by the author's tooling. Regenerable.

DELETE FROM `spell_dbc` WHERE `ID` BETWEEN 903000 AND 903999;
INSERT INTO `spell_dbc` (`ID`, `Attributes`, `AttributesEx`, `CastingTimeIndex`, `ProcChance`, `DurationIndex`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectDieSides_1`, `EffectBasePoints_1`, `ImplicitTargetA_1`, `EffectAura_1`, `EffectMiscValue_1`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_koKR`, `Name_Lang_Mask`, `Description_Lang_enUS`, `Description_Lang_koKR`, `Description_Lang_Mask`, `AuraDescription_Lang_enUS`, `AuraDescription_Lang_koKR`, `AuraDescription_Lang_Mask`, `SchoolMask`) VALUES
(903000, 0, 0, 1, 101, 0, 1, -1, 3, 1, 0, 1, 0, 0, 1, 'Study the card', 'Étudier la carte', 255, 'Study this card: it joins the binder of every character of your account. The card is consumed.', 'Étudier cette carte : elle rejoint le classeur de tous les personnages de votre compte. La carte est consommée.', 255, '', '', 0, 1),
(903001, 0, 0, 1, 101, 0, 1, -1, 3, 1, 0, 1, 0, 0, 1, 'Study the board', 'Étudier le plateau', 255, 'Study this board: it joins the binder of every character of your account. The board is consumed.', 'Étudier ce plateau : il rejoint le classeur de tous les personnages de votre compte. Le plateau est consommé.', 255, '', '', 0, 1),
(903002, 2147483648, 0, 1, 101, 21, 1, -1, 6, 1, 0, 1, 4, 0, 1, 'Stellar Tarot', 'Tarot stellaire', 255, 'The cards laid on your board grant their effects. Open the tarot window (/tarot) to see them.', 'Les cartes posées sur votre plateau vous accordent leurs effets. Ouvrez la fenêtre du tarot (/tarot) pour les voir.', 255, 'The cards laid on your board grant their effects.', 'Les cartes posées sur votre plateau vous accordent leurs effets.', 255, 1),
(903004, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 2, 1, 'The Star (level 1)', 'L''Étoile (niveau 1)', 255, '+$s1 Stamina', '+$s1 Endurance', 255, '+$s1 Stamina', '+$s1 Endurance', 255, 1),
(903005, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 0, 1, 'The Star (level 2)', 'L''Étoile (niveau 2)', 255, '+$s1 Strength', '+$s1 Force', 255, '+$s1 Strength', '+$s1 Force', 255, 1),
(903006, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 1, 1, 'The Star (level 3)', 'L''Étoile (niveau 3)', 255, '+$s1 Agility', '+$s1 Agilité', 255, '+$s1 Agility', '+$s1 Agilité', 255, 1),
(903007, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 3, 1, 'The Star (level 4)', 'L''Étoile (niveau 4)', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, 1),
(903008, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 2, 1, 'The Moon (level 1)', 'La Lune (niveau 1)', 255, '+$s1 Stamina', '+$s1 Endurance', 255, '+$s1 Stamina', '+$s1 Endurance', 255, 1),
(903009, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 0, 1, 'The Moon (level 2)', 'La Lune (niveau 2)', 255, '+$s1 Strength', '+$s1 Force', 255, '+$s1 Strength', '+$s1 Force', 255, 1),
(903010, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 1, 1, 'The Moon (level 3)', 'La Lune (niveau 3)', 255, '+$s1 Agility', '+$s1 Agilité', 255, '+$s1 Agility', '+$s1 Agilité', 255, 1),
(903011, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 3, 1, 'The Moon (level 4)', 'La Lune (niveau 4)', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, 1),
(903012, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 2, 1, 'The Sun (level 1)', 'Le Soleil (niveau 1)', 255, '+$s1 Stamina', '+$s1 Endurance', 255, '+$s1 Stamina', '+$s1 Endurance', 255, 1),
(903013, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 0, 1, 'The Sun (level 2)', 'Le Soleil (niveau 2)', 255, '+$s1 Strength', '+$s1 Force', 255, '+$s1 Strength', '+$s1 Force', 255, 1),
(903014, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 1, 1, 'The Sun (level 3)', 'Le Soleil (niveau 3)', 255, '+$s1 Agility', '+$s1 Agilité', 255, '+$s1 Agility', '+$s1 Agilité', 255, 1),
(903015, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 3, 1, 'The Sun (level 4)', 'Le Soleil (niveau 4)', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, 1),
(903016, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 2, 1, 'The Comet (level 1)', 'La Comète (niveau 1)', 255, '+$s1 Stamina', '+$s1 Endurance', 255, '+$s1 Stamina', '+$s1 Endurance', 255, 1),
(903017, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 0, 1, 'The Comet (level 2)', 'La Comète (niveau 2)', 255, '+$s1 Strength', '+$s1 Force', 255, '+$s1 Strength', '+$s1 Force', 255, 1),
(903018, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 1, 1, 'The Comet (level 3)', 'La Comète (niveau 3)', 255, '+$s1 Agility', '+$s1 Agilité', 255, '+$s1 Agility', '+$s1 Agilité', 255, 1),
(903019, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 3, 1, 'The Comet (level 4)', 'La Comète (niveau 4)', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, 1),
(903020, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 2, 1, 'The Eclipse (level 1)', 'L''Éclipse (niveau 1)', 255, '+$s1 Stamina', '+$s1 Endurance', 255, '+$s1 Stamina', '+$s1 Endurance', 255, 1),
(903021, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 0, 1, 'The Eclipse (level 2)', 'L''Éclipse (niveau 2)', 255, '+$s1 Strength', '+$s1 Force', 255, '+$s1 Strength', '+$s1 Force', 255, 1),
(903022, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 1, 1, 'The Eclipse (level 3)', 'L''Éclipse (niveau 3)', 255, '+$s1 Agility', '+$s1 Agilité', 255, '+$s1 Agility', '+$s1 Agilité', 255, 1),
(903023, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 3, 1, 'The Eclipse (level 4)', 'L''Éclipse (niveau 4)', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, 1),
(903024, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 2, 1, 'The Nebula (level 1)', 'La Nébuleuse (niveau 1)', 255, '+$s1 Stamina', '+$s1 Endurance', 255, '+$s1 Stamina', '+$s1 Endurance', 255, 1),
(903025, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 0, 1, 'The Nebula (level 2)', 'La Nébuleuse (niveau 2)', 255, '+$s1 Strength', '+$s1 Force', 255, '+$s1 Strength', '+$s1 Force', 255, 1),
(903026, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 1, 1, 'The Nebula (level 3)', 'La Nébuleuse (niveau 3)', 255, '+$s1 Agility', '+$s1 Agilité', 255, '+$s1 Agility', '+$s1 Agilité', 255, 1),
(903027, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 3, 1, 'The Nebula (level 4)', 'La Nébuleuse (niveau 4)', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, 1),
(903028, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 2, 1, 'The Void (level 1)', 'Le Vide (niveau 1)', 255, '+$s1 Stamina', '+$s1 Endurance', 255, '+$s1 Stamina', '+$s1 Endurance', 255, 1),
(903029, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 0, 1, 'The Void (level 2)', 'Le Vide (niveau 2)', 255, '+$s1 Strength', '+$s1 Force', 255, '+$s1 Strength', '+$s1 Force', 255, 1),
(903030, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 1, 1, 'The Void (level 3)', 'Le Vide (niveau 3)', 255, '+$s1 Agility', '+$s1 Agilité', 255, '+$s1 Agility', '+$s1 Agilité', 255, 1),
(903031, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 3, 1, 'The Void (level 4)', 'Le Vide (niveau 4)', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, 1),
(903032, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 2, 1, 'The Wanderer (level 1)', 'Le Vagabond (niveau 1)', 255, '+$s1 Stamina', '+$s1 Endurance', 255, '+$s1 Stamina', '+$s1 Endurance', 255, 1),
(903034, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 1, 1, 'The Wanderer (level 3)', 'Le Vagabond (niveau 3)', 255, '+$s1 Agility', '+$s1 Agilité', 255, '+$s1 Agility', '+$s1 Agilité', 255, 1),
(903035, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 3, 1, 'The Wanderer (level 4)', 'Le Vagabond (niveau 4)', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, 1),
(903036, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 2, 1, 'The Twins (level 1)', 'Les Jumeaux (niveau 1)', 255, '+$s1 Stamina', '+$s1 Endurance', 255, '+$s1 Stamina', '+$s1 Endurance', 255, 1),
(903037, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 0, 1, 'The Twins (level 2)', 'Les Jumeaux (niveau 2)', 255, '+$s1 Strength', '+$s1 Force', 255, '+$s1 Strength', '+$s1 Force', 255, 1),
(903038, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 1, 1, 'The Twins (level 3)', 'Les Jumeaux (niveau 3)', 255, '+$s1 Agility', '+$s1 Agilité', 255, '+$s1 Agility', '+$s1 Agilité', 255, 1),
(903039, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 3, 1, 'The Twins (level 4)', 'Les Jumeaux (niveau 4)', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, 1),
(903040, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 2, 1, 'The Serpent (level 1)', 'Le Serpent (niveau 1)', 255, '+$s1 Stamina', '+$s1 Endurance', 255, '+$s1 Stamina', '+$s1 Endurance', 255, 1),
(903041, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 0, 1, 'The Serpent (level 2)', 'Le Serpent (niveau 2)', 255, '+$s1 Strength', '+$s1 Force', 255, '+$s1 Strength', '+$s1 Force', 255, 1),
(903042, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 1, 1, 'The Serpent (level 3)', 'Le Serpent (niveau 3)', 255, '+$s1 Agility', '+$s1 Agilité', 255, '+$s1 Agility', '+$s1 Agilité', 255, 1),
(903043, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 3, 1, 'The Serpent (level 4)', 'Le Serpent (niveau 4)', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, 1),
(903044, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 2, 1, 'The Lantern (level 1)', 'La Lanterne (niveau 1)', 255, '+$s1 Stamina', '+$s1 Endurance', 255, '+$s1 Stamina', '+$s1 Endurance', 255, 1),
(903045, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 0, 1, 'The Lantern (level 2)', 'La Lanterne (niveau 2)', 255, '+$s1 Strength', '+$s1 Force', 255, '+$s1 Strength', '+$s1 Force', 255, 1),
(903046, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 1, 1, 'The Lantern (level 3)', 'La Lanterne (niveau 3)', 255, '+$s1 Agility', '+$s1 Agilité', 255, '+$s1 Agility', '+$s1 Agilité', 255, 1),
(903047, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 3, 1, 'The Lantern (level 4)', 'La Lanterne (niveau 4)', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, 1),
(903051, 2147483648, 268435456, 1, 101, 21, 1, -1, 6, 1, 1233, 1, 29, 3, 1, 'The Tide (level 4)', 'La Marée (niveau 4)', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, '+$s1 Intellect', '+$s1 Intelligence', 255, 1);
